require:
  - rubocop-rake

AllCops:
  Include:
    - Capfile
    - Gemfile
    - Rakefile
    - config.ru
    - '**/*.rb'
  Exclude:
    - 'db/schema.rb'
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'script/console'
