<%
  def user_for(host)
    Net::SSH::Config.for(host).fetch(:user, ENV.fetch('USER', nil))
  end

  def ruby_version
    project_root.join('.ruby-version').read.strip
  end

  def project_root
    KAMAL.instance_variable_get(:@config_kwargs)[:config_file].join('../..')
  end
%>

service: url-shortener
image: werebus/url-shortener

servers:
  web:
    - apps.wereb.us

ssh:
  user: <%= user_for 'apps.wereb.us' %>

proxy:
  ssl: true
  host: mm.vu

registry:
  server: ghcr.io
  username: werebus
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  args:
    RUBY_VERSION: <%= ruby_version %>

env:
  clear:
    DEFAULT_URL: 'https://wereb.us/'
    LOG_LEVEL: 'info'
  secret:
    - DATABASE_URL
    - SECRET
